apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  labels:
    app: sovos-rabbitmq
  name: sovos-rabbitmq
spec:
  replicas: 3
  service:
    type: ClusterIP
  image: rabbitmq:3.9.20
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi
  terminationGracePeriodSeconds: 60
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_prometheus
      - rabbitmq_peer_discovery_k8s
    additionalConfig: |
      cluster_partition_handling = autoheal
      log.console.level = info
      log.file.level = info
      vm_memory_high_watermark_paging_ratio = 0.85
      vm_memory_high_watermark.relative = 0.7
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
      cluster_formation.node_cleanup.interval = 30
      cluster_formation.node_cleanup.only_log_warning = true
      queue_master_locator = min-masters
  persistence:
    storageClassName: vmware2
    storage: "250Mi"
